// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
// step 1: recieving n and determining new arguments
		int n = Integer.parseInt(args[0]);
		int greater = 0;
		int under = 0;
// step 2: generating a random number
			for (int i = 0; i < n; i++) {
			double r = Math.random();
// step 3: counting times greater or under 0.5
				if (r < 0.5) {
					under++;
				} else {
					greater++;
				}
			}
// step 4: ratio calculation and edge case handling, then printing
		double ratio = -1.0;
		System.out.println("> 0.5: " + greater);
		System.out.println("<= 0.5: " + under);
		if (under != 0 && greater != 0) {
		ratio = (double) greater / under;
		System.out.println("Ratio: " + ratio);
		}
}
}